### PR TITLE
Improvements [v0.6]

### PR DESCRIPTION
**Pull request by sharkykh**
## TODO:
- [x] Add option to use already installed `git` - it should verify that git is available on Path and get `git.exe` path. Or maybe add git path to options page.
- [x] Same as above, only this time for Python. ~Additionally should check that the version is >= 3.5.2 (if easily doable)~.
- [x] For Python, instead of using the custom executable directly, it should probably create a `virtualenv` (as `{app}\Python`?)
- [x] Create an initial `{app}\Data\config.ini` with the port number set in it - to fix being unable to change the port from the WebUI after installation (https://github.com/pymedusa/Medusa/issues/3987). Although the links generated by the install won't be changed and may cause some confusion. 
- [x] Update readme and welcome message - remove "This installer intentionally ignores any existing..."

## Screenshots
<details>

MedusaInstaller-1
---
### The "path to..." options only show up if you deselect the Python / Git components.
MedusaInstaller-2
---
MedusaInstaller-3

</details>

### CODE REVIEW

**Comment by sharkykh** [comment]
Not sure why it says that:
image


Maybe it's just because the PR is a draft right now.

**Comment by p0psicles** [comment]
Can you include the commit in the name? In the past I used like name-date-commit

**Comment by sharkykh** [comment]
@p0psicles In what name?

**Comment by p0psicles** [comment]
MedusaInstaller filename / artifact

**Comment by sharkykh** [comment]
I don't remember if I can rename the file when uploading the artifacts,
(well, I guess I can always rename it manually...)
but I can rename it for the releases (when it adds it to a release draft).

For the release itself - since there are versions (..., `v0.5`, `v0.6`), why not just use these?

**Comment by p0psicles** [comment]
Ooh yeah releases should just have semver. I meant for snapshots

**Comment by sharkykh** [comment]
Date and commit will look too weird:
`Output\MedusaInstaller-v0.6-2019-06-22T00:00:18.7209280+03:00-36cbab541.exe`
I added just the commit:
`Output\MedusaInstaller-36cbab541.exe`

**Comment by sharkykh** [comment]
Date and commit will look too weird:
`Output\MedusaInstaller-2019-06-22T00:00:18.7209280+03:00-36cbab541.exe`
I added just the commit:
`Output\MedusaInstaller-36cbab541.exe`

@p0psicles

**Comment by sharkykh** [comment]
## Please test it before merging!

**Comment by sharkykh** [comment]
Argh. It downloads both the dependencies when you select just one of them.
I need to reorganize that code.
So... not done.

**Review by medariox — APPROVED** [review]
Everything seems to work perfectly on my end. Awesome work! 👍

**Pull request merged**
